"""add credits

Revision ID: 0e675a4b5559
Revises: 928946a7bd93
Create Date: 2025-11-13 17:51:08.864529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e675a4b5559'
down_revision: Union[str, Sequence[str], None] = '928946a7bd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type', postgresql.ENUM('OCR_TEXT_EXTRACTION', 'LATEX_COMPILATION', 'AI_TEXT_IMPROVEMENT', 'AI_LATEX_FIXING', 'DIAGRAM_GENERATION', 'TABLE_GENERATION', name='servicetype'), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('plan_type', postgresql.ENUM('FREE', 'PRO', 'TEAM', name='plantype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('PURCHASE', 'USAGE', 'REFUND', 'BONUS', 'DAILY_RESET', name='transactiontype'), nullable=False),
    sa.Column('service_type', postgresql.ENUM('OCR_TEXT_EXTRACTION', 'LATEX_COMPILATION', 'AI_TEXT_IMPROVEMENT', 'AI_LATEX_FIXING', 'DIAGRAM_GENERATION', 'TABLE_GENERATION', name='servicetype'), nullable=True),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('available_credits', sa.Integer(), nullable=False),
    sa.Column('daily_credits', sa.Integer(), nullable=False),
    sa.Column('purchased_credits', sa.Integer(), nullable=False),
    sa.Column('last_daily_reset', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', postgresql.ENUM('FREE', 'PRO', 'TEAM', name='plantype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriptions')
    op.drop_table('user_credits')
    op.drop_table('credit_transactions')
    op.drop_table('service_pricing')
    # ### end Alembic commands ###
