"""colaborator

Revision ID: 66e846e9cca3
Revises: 30b3e1a4d159
Create Date: 2025-12-30 18:52:19.889520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66e846e9cca3'
down_revision: Union[str, Sequence[str], None] = '30b3e1a4d159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_collaborators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('invited_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_collaborators_invited_email'), 'project_collaborators', ['invited_email'], unique=False)
    op.create_index(op.f('ix_project_collaborators_project_id'), 'project_collaborators', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_collaborators_user_id'), 'project_collaborators', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_collaborators_user_id'), table_name='project_collaborators')
    op.drop_index(op.f('ix_project_collaborators_project_id'), table_name='project_collaborators')
    op.drop_index(op.f('ix_project_collaborators_invited_email'), table_name='project_collaborators')
    op.drop_table('project_collaborators')
    # ### end Alembic commands ###
