"""document

Revision ID: 938e5181caa3
Revises: d2b3c4d5e6f7
Create Date: 2025-12-30 15:50:29.847821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '938e5181caa3'
down_revision: Union[str, Sequence[str], None] = 'd2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    # --- create enums (safe) ---
    try:
        sa.Enum("LATEX", "TIKZ", "MARKDOWN", "TEXT", "IMAGE", "PDF", name="filetype").create(bind)
    except Exception:
        pass

    try:
        sa.Enum("DRAFT", "IN_PROGRESS", "COMPLETED", "ARCHIVED", name="projectstatus").create(bind)
    except Exception:
        pass

    try:
        sa.Enum(
            "TABLE", "DIAGRAM", "IMAGE_TO_LATEX", "HANDWRITTEN_FLOWCHART", "DOCUMENT",
            name="subprojecttype"
        ).create(bind)
    except Exception:
        pass

    # --- normalize existing data to match enums ---
    op.execute("UPDATE project_files SET file_type = UPPER(file_type) WHERE file_type IS NOT NULL")
    op.execute("UPDATE projects SET status = UPPER(status) WHERE status IS NOT NULL")
    op.execute("UPDATE sub_projects SET sub_project_type = UPPER(sub_project_type) WHERE sub_project_type IS NOT NULL")

    # ==========================================================
    # IMPORTANT FIX: remove old VARCHAR defaults BEFORE type cast
    # ==========================================================

    # project_files.file_type default: 'text'::varchar -> must be dropped first
    op.alter_column("project_files", "file_type", server_default=None)

    # projects.status default: 'draft'::varchar -> must be dropped first
    op.alter_column("projects", "status", server_default=None)

    # --- now convert to enums (explicit cast) ---
    op.execute(
        "ALTER TABLE project_files "
        "ALTER COLUMN file_type TYPE filetype "
        "USING file_type::filetype"
    )

    op.execute(
        "ALTER TABLE projects "
        "ALTER COLUMN status TYPE projectstatus "
        "USING status::projectstatus"
    )

    op.execute(
        "ALTER TABLE sub_projects "
        "ALTER COLUMN sub_project_type TYPE subprojecttype "
        "USING sub_project_type::subprojecttype"
    )

    # --- re-add correct enum defaults (must match enum labels) ---
    op.alter_column(
        "project_files",
        "file_type",
        server_default=sa.text("'TEXT'::filetype"),
        existing_nullable=False,
    )

    op.alter_column(
        "projects",
        "status",
        server_default=sa.text("'DRAFT'::projectstatus"),
        existing_nullable=False,
    )

    # --- keep the rest of your autogenerated changes (unchanged) ---
    op.alter_column(
        "project_files", "content",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True
    )
    op.alter_column(
        "project_files", "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.alter_column(
        "project_files", "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.drop_index(op.f("ix_project_files_file_type"), table_name="project_files")
    op.drop_constraint(op.f("project_files_project_id_fkey"), "project_files", type_="foreignkey")
    op.create_foreign_key(None, "project_files", "projects", ["project_id"], ["id"])

    op.alter_column(
        "projects", "description",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
        existing_nullable=True
    )
    op.alter_column(
        "projects", "latex_content",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True
    )
    op.alter_column(
        "projects", "tags",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True
    )
    op.alter_column(
        "projects", "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.alter_column(
        "projects", "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_constraint(op.f("projects_user_id_fkey"), "projects", type_="foreignkey")
    op.create_foreign_key(None, "projects", "users", ["user_id"], ["id"])

    op.alter_column(
        "sub_project_file_links", "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.drop_constraint(op.f("sub_project_file_links_project_file_id_fkey"), "sub_project_file_links", type_="foreignkey")
    op.drop_constraint(op.f("sub_project_file_links_sub_project_id_fkey"), "sub_project_file_links", type_="foreignkey")
    op.create_foreign_key(None, "sub_project_file_links", "project_files", ["project_file_id"], ["id"])
    op.create_foreign_key(None, "sub_project_file_links", "sub_projects", ["sub_project_id"], ["id"])

    op.alter_column(
        "sub_projects", "description",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True
    )
    op.alter_column(
        "sub_projects", "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.alter_column(
        "sub_projects", "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()")
    )
    op.drop_constraint(op.f("sub_projects_project_id_fkey"), "sub_projects", type_="foreignkey")
    op.drop_constraint(op.f("sub_projects_source_file_id_fkey"), "sub_projects", type_="foreignkey")
    op.drop_constraint(op.f("sub_projects_user_id_fkey"), "sub_projects", type_="foreignkey")
    op.create_foreign_key(None, "sub_projects", "project_files", ["source_file_id"], ["id"])
    op.create_foreign_key(None, "sub_projects", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "sub_projects", "projects", ["project_id"], ["id"])