"""add marketplace tables

Revision ID: a7f4553b6e60
Revises: 46ea5db55a78
Create Date: 2026-01-11 19:38:08.868893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7f4553b6e60'
down_revision: Union[str, Sequence[str], None] = '46ea5db55a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketplace_categories_slug'), 'marketplace_categories', ['slug'], unique=True)
    op.create_table('marketplace_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Enum('TEMPLATE', 'SNIPPET', 'PACKAGE_CONFIG', name='marketplaceitemtype'), nullable=False),
    sa.Column('latex_content', sa.Text(), nullable=True),
    sa.Column('preamble', sa.Text(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('preview_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_category_id'), 'marketplace_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_items_slug'), 'marketplace_items', ['slug'], unique=True)
    op.create_index(op.f('ix_marketplace_items_user_id'), 'marketplace_items', ['user_id'], unique=False)
    op.create_table('marketplace_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_reviews_item_id'), 'marketplace_reviews', ['item_id'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_user_id'), 'marketplace_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_reviews_user_id'), table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_item_id'), table_name='marketplace_reviews')
    op.drop_table('marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_items_user_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_slug'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category_id'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index(op.f('ix_marketplace_categories_slug'), table_name='marketplace_categories')
    op.drop_table('marketplace_categories')
    # ### end Alembic commands ###
